name: aws_interop
description: Dart wrapper for Amazon AWS
version: 2.0.1
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://www.github.com/johnpryan/aws-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: '>=0.6.0 <1.0.0'

dev_dependencies:
  test:
  jsifier: any
